// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 

import 'package:firebase_core/firebase_core.dart';



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcpu074pHv6ozj7ncjcwtQgLsrCsROVKA',
    appId: '1:216381597262:web:441ff1b3b960e5eb0f451f',
    messagingSenderId: '216381597262',
    projectId: 'eco-collect-app-41a25',
    authDomain: 'eco-collect-app-41a25.firebaseapp.com',
    storageBucket: 'eco-collect-app-41a25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC2tkNNsROmR1UFZ6Tvk02RwVZB7Fj608',
    appId: '1:216381597262:android:466567dde9a74f040f451f',
    messagingSenderId: '216381597262',
    projectId: 'eco-collect-app-41a25',
    storageBucket: 'eco-collect-app-41a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfz67TeA43F8TwKX1fDYz7J9Uam1g-jI',
    appId: '1:216381597262:ios:ffe6c0759d029f4e0f451f',
    messagingSenderId: '216381597262',
    projectId: 'eco-collect-app-41a25',
    storageBucket: 'eco-collect-app-41a25.firebasestorage.app',
    iosBundleId: 'com.example.ecocollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfz67TeA43F8TwKX1fDYz7J9Uam1g-jI',
    appId: '1:216381597262:ios:ffe6c0759d029f4e0f451f',
    messagingSenderId: '216381597262',
    projectId: 'eco-collect-app-41a25',
    storageBucket: 'eco-collect-app-41a25.firebasestorage.app',
    iosBundleId: 'com.example.ecocollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcpu074pHv6ozj7ncjcwtQgLsrCsROVKA',
    appId: '1:216381597262:web:fb9ac15fcb645a7f0f451f',
    messagingSenderId: '216381597262',
    projectId: 'eco-collect-app-41a25',
    authDomain: 'eco-collect-app-41a25.firebaseapp.com',
    storageBucket: 'eco-collect-app-41a25.firebasestorage.app',
  );
}
